# Generated by Django 4.2.6 on 2023-11-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_alter_event_user'),
        ('users', '0007_rename_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
