# Generated by Django 4.2.4 on 2023-10-31 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_rename_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=500)),
                ('location_name', models.CharField(max_length=100)),
                ('event_address', models.CharField(max_length=200)),
                ('event_time', models.CharField(max_length=50)),
                ('event_date', models.CharField(max_length=50)),
                ('point_of_contact', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
