# Generated by Django 4.2.4 on 2023-11-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.CharField(default='38.03172018123903', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.CharField(default='-78.51068497101028', max_length=50),
            preserve_default=False,
        ),
    ]
