# Generated by Django 4.2.4 on 2023-11-04 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_event_user'),
        ('map', '0004_alter_event_user'),
    ]

    operations = [
    ]
