# Generated by Django 4.2.4 on 2023-11-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_event_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('academic', 'ACADEMIC'), ('art', 'ART'), ('career', 'CAREER'), ('club', 'CLUB'), ('food', 'FOOD'), ('music', 'MUSIC'), ('social', 'SOCIAL'), ('sports', 'SPORTS'), ('volunteering', 'VOLUNTEERING'), ('other', 'OTHER')], max_length=50),
        ),
    ]
