# Generated by Django 4.2.4 on 2023-11-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_remove_event_event_date_remove_event_event_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='requirements',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
