# Generated by Django 4.2.4 on 2023-11-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_alter_event_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='requirements',
            field=models.CharField(default='', max_length=500),
        ),
    ]
