# Generated by Django 4.2.4 on 2023-11-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_alter_event_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deny_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
