# Generated by Django 4.2.4 on 2023-12-02 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_alter_event_event_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
